Repository acm-ucr/senior-design-website, pull requests merged in 2024-02, with the labels that each got.

#46 Kevinloritsch/projectTypesError
  src/components/landing/ProjectType.jsx
Labels: Ready to review

#45 fixed sample filter buttons
  src/components/landing/Landing.jsx
  src/components/projects/filterbuttons.jsx
Labels: Ready to review

#44 brianubyun/titlecomponent
  src/components/details/Details.jsx
  src/components/details/Title.jsx
Labels: Ready to review, front end

#37 Brianubyun/thumbnailpage
  src/components/details/Details.jsx
Labels: Ready to review, front end

#50 Kevinloritsch/removeMenu
  src/components/Navigation.jsx
Labels: Ready to review

#52 Brianubyun/move footer
  src/app/layout.js
  src/components/Footer.jsx
  src/components/landing/Landing.jsx
Labels: front end

#32 Christophergipson/fakedata
  src/components/landing/PastProjects.jsx
  src/components/projectcard.jsx
  src/components/testcomponent.jsx
  src/data/fakedata.js
  src/data/projectcard.jsx
  src/data/testcomponent.jsx
Labels: Ready to review

#51 Kevinloritsch/projectSection
  src/components/landing/ProjectType.jsx
Labels: Ready to review

#63 Kevinloritsch/addProjectCardstoProjectPage
  src/app/projects/page.js
  src/components/projects/ProjectCards.jsx
  src/data/fakedata.js
Labels: Ready to review

#66 Brianubyun/fix project type
  src/components/landing/ProjectType.jsx
Labels: landing, front end

#71 view more component
  src/components/ViewMore.jsx
Labels: Ready to review
