Repository acm-ucr/senior-design-website, pull requests merged in 2024-03, with the labels that each got.

#53 stanley/searchbar
  package-lock.json
  package.json
  src/app/projects/page.js
  src/components/projects/Search.jsx
  src/components/projects/filterbuttons.jsx
Labels: Ready to review

#76 still white space under
  public/figma.png
  src/components/details/Title.jsx
Labels: Do Not Merge

#80 added project thumbnail
  src/components/projects/ProjectThumbnail.jsx
Labels: front end, Projects pg

#78 Kevinloritsch/detailsData
  src/components/details/Details.jsx
  src/data/fakedetailsdata.js
Labels: Ready to review

#70 added responsive design for projects/details
  public/svg/operating-systems.svg
  src/components/details/Details.jsx
  src/components/landing/Landing.jsx
  src/components/landing/PastProjects.jsx
  src/components/landing/ProjectType.jsx
  src/components/projectcard.jsx
Labels: Ready to review

#72 added welcome
  src/components/landing/Welcome.jsx
Labels: front end

#95 JohnZ/Search
  src/app/projects/page.js
  src/components/projects/ProjectCards.jsx
  src/components/projects/Projects.jsx
  src/components/projects/Search.jsx
  src/components/projects/filterbuttons.jsx
  src/data/fakedata.json
Labels: Ready to review

#97 fixed view button
  src/components/ViewMore.jsx
Labels: bug, front end

#96 Michellesun2/margin fix ups
  src/components/landing/About.jsx
  src/components/projects/Search.jsx
Labels: front end

#94 Kevinloritsch/photos
  public/stockphoto1.jpg
  public/stockphoto2.jpg
  public/stockphoto3.jpg
  src/components/details/Details.jsx
  src/components/landing/PastProjects.jsx
  src/components/projectcard.jsx
  src/components/projects/ProjectCards.jsx
  src/components/projects/ProjectThumbnail.jsx
  src/components/projects/filterbuttons.jsx
Labels: Ready to review

#105 Pagination, Searching, Landing
  package-lock.json
  package.json
  src/app/layout.js
  src/app/projects/details/page.js
  src/app/projects/page.js
  src/components/Footer.jsx
  src/components/Project.jsx
  src/components/ViewMore.jsx
  src/components/details/Content.jsx
  src/components/details/Details.jsx
  src/components/details/Title.jsx
  src/components/landing/About.jsx
  src/components/landing/Landing.jsx
  src/components/landing/PastProjects.jsx
  src/components/landing/Welcome.jsx
  src/components/projectcard.jsx
  src/components/projects/Cards.jsx
  src/components/projects/Pagination.jsx
  src/components/projects/ProjectCards.jsx
  src/components/projects/ProjectThumbnail.jsx
  src/components/projects/Projects.jsx
  src/components/projects/Search.jsx
  src/components/projects/filterbuttons.jsx
  src/data/details.js
  src/data/fakedata.json
  src/data/fakedetailsdata.js
  src/data/projects.json
Labels: Ready to review
