Repository acm-ucr/senior-design-website, pull requests merged in 2024-01, with the labels that each got.

#17 Kevinloritsch/About
  src/components/landing/About.jsx
  tailwind.config.js
Labels: Ready to review

#18 brianubyun/Footer
  src/components/Footer.jsx
Labels: Ready to review, landing

#26 types of projects page
  src/components/landing/ProjectType.jsx
  tailwind.config.js
Labels: Ready to review

#24 added nav bar
  package-lock.json
  package.json
  src/app/layout.js
  src/components/Navbar.jsx
  src/components/Navigation.jsx
  src/components/landing/Landing.jsx
Labels: Ready to review

#21 Kevinloritsch/search
  src/components/projects/Search.jsx
Labels: Ready to review

#34 filter buttons, created another branch for easier review
  src/app/projects/page.js
  src/components/projects/filterbuttons.jsx
  tailwind.config.js
Labels: Ready to review

#35 Kevinloritsch/detailTitle
  src/components/details/Title.jsx
Labels: help wanted

#33 body section for details page
  public/tempimage.png
  src/components/details/Details.jsx
Labels: Ready to review

#19 added image at 100% size
  src/components/landing/Welcome.jsx
Labels: Ready to review
